apiVersion: v1
kind: Service
metadata:
  name: pizza-api-service
  labels:
    app: pizza-api
spec:
  type: ClusterIP
  selector:
    app: pizza-api
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
